#!/bin/bash

# This script compiles the .spad files and creates a script
# "loadlibs.input" to load the respective libraries into a FriCAS
# session.

# Only change the directory in a subshell.
(cd p; make compile-spad)

cat <<EOF > loadlibs.input
)cd p/tmp
)read projectlibs
)read etamacros
EOF
