#!/bin/bash

# This script compiles the .spad files and creates a script
# "loadlibs.input" to load the respective libraries into a FriCAS
# session.

# Only change the directory in a subshell.
(cd p; make compile-spad)

# Copy additional macro definitions to the spadunit directory.
cp p/input/convenience.input .
cp p/input/modfuns.input .

cat <<EOF > loadlibs.input
)cd p/tmp
)read projectlibs
)read etamacros
EOF
