#!/bin/bash

# This script compiles the .spad files and creates a script
# "loadlibs.input" to load the respective libraries into a FriCAS
# session.

# Only change the directory in a subshell.
(cd p; make compile-spad)

# Copy additional macro definitions to the spadunit directory.
cp p/input/convenience.input .
cp p/input/modfuns.input .

cat <<EOF > loadlibs.input
)cd p/tmp
)read projectlibs )quiet
)read qetamacros )quiet
-- To get unique filename during call of zsolve$X4ti2.
-- )lisp (setf *random-state* (make-random-state t))
seedRandom()$Integer
EOF
